FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps --silent && npm cache clean --force
RUN npm install better-sqlite3 --silent

COPY . .

EXPOSE 3000 24678
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD ["npm", "run", "dev"]
