FROM node:18-alpine

WORKDIR /app
RUN apk add --no-cache git

COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY . .

EXPOSE 3000 24678
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD ["npm", "run", "dev"]
